apiVersion: garm-operator.mercedes-benz.com/v1beta1
kind: GarmServerConfig
metadata:
  name: garm-server-config
  namespace: garm-operator-system
spec:
  callbackUrl: http://garm-server.garm-server.svc:9997/api/v1/callbacks
  metadataUrl: http://garm-server.garm-server.svc:9997/api/v1/metadata
  webhookUrl: http://garm-server.garm-server.svc:9997/api/v1/webhook
---
apiVersion: garm-operator.mercedes-benz.com/v1beta1
kind: GitHubEndpoint
metadata:
  name: github
  namespace: garm-operator-system
spec:
  description: "github.com"
  apiBaseUrl: $GARM_GITHUB_API_BASE_URL
  uploadBaseUrl: $GARM_GITHUB_UPLOAD_BASE_URL
  baseUrl: $GARM_GITHUB_BASE_URL
---
apiVersion: garm-operator.mercedes-benz.com/v1beta1
kind: GitHubCredential
metadata:
  name: github-pat
  namespace: garm-operator-system
spec:
  description: credentials for github
  endpointRef:
    apiGroup: garm-operator.mercedes-benz.com
    kind: GitHubEndpoint
    name: github
  authType: pat
  secretRef:
    name: github-pat
    key: token
---
apiVersion: v1
kind: Secret
metadata:
  name: github-pat
  namespace: garm-operator-system
data:
  token: $GARM_GITHUB_TOKEN
---
apiVersion: garm-operator.mercedes-benz.com/v1beta1
kind: Repository
metadata:
  labels:
    app.kubernetes.io/name: repository
    app.kubernetes.io/instance: repository-sample
    app.kubernetes.io/part-of: garm-operator
  name: $GARM_GITHUB_REPOSITORY
  namespace: garm-operator-system
spec:
  webhookSecretRef:
    key: "webhookSecret"
    name: "repo-webhook-secret"
  credentialsRef:
    apiGroup: garm-operator.mercedes-benz.com
    kind: GitHubCredentials
    name: github-pat
  owner: $GARM_GITHUB_ORGANIZATION
---
apiVersion: v1
kind: Secret
metadata:
  name: repo-webhook-secret
  namespace: garm-operator-system
data:
  webhookSecret: $GARM_GITHUB_WEBHOOK_SECRET
---
apiVersion: garm-operator.mercedes-benz.com/v1beta1
kind: Image
metadata:
  labels:
    app.kubernetes.io/name: image
    app.kubernetes.io/instance: image-sample
    app.kubernetes.io/part-of: garm-operator
  name: runner-default
  namespace: garm-operator-system
spec:
  tag: $RUNNER_IMAGE
---
apiVersion: garm-operator.mercedes-benz.com/v1beta1
kind: Pool
metadata:
  name: kubernetes-pool-repo
  namespace: garm-operator-system
spec:
  githubScopeRef:
    apiGroup: garm-operator.mercedes-benz.com
    kind: Repository
    name: $GARM_GITHUB_REPOSITORY
  enabled: true
  flavor: medium
  extraSpecs: '{}'
  githubRunnerGroup: ""
  imageName: runner-default
  maxRunners: 2
  minIdleRunners: 1
  osArch: amd64
  osType: linux
  providerName: kubernetes_external
  runnerBootstrapTimeout: 2
  runnerPrefix: "garm-k8s"
  tags:
    - linux-ubuntu-22.04-x86_64
