apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garm-data
  namespace: garm-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: garm-home
  namespace: garm-server
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
