# SPDX-License-Identifier: MIT

linters:
  disable-all: true
  fast: false
  enable:
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - godox
    - govet
    - gosec
    - importas
    - ineffassign
    - loggercheck
    - misspell
    - nakedret
    - nilerr
    - predeclared
    - promlinter
    - revive
    - staticcheck
    - tagliatelle
    - unconvert
    - unused
    - wastedassign
    - whitespace

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/mercedes-benz/garm-provider-k8s)

  goimports:
    local-prefixes: github.com/mercedes-benz/garm-provider-k8s

  importas:
    no-unaliased: false
    alias:
      - pkg: k8s.io/api/core/v1
        alias: corev1
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: metav1

  loggercheck:
    klog: true
    zap: false
    require-string-key: true
    no-printf-like: true
