name: Bug Report
description: Report a bug encountered while using garm operator
body:
  - type: textarea
    id: problem
    attributes:
      label: What steps did you take and what happened?
      description: |
        Please provide as much info as possible about the problem.
      placeholder: "A clear and concise description on how to REPRODUCE the bug."
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: garmVersion
    attributes:
      label: garm version
      placeholder: "The version of garm used in your environment"
    validations:
      required: true

  - type: textarea
    id: garmOperatorVersion
    attributes:
      label: garm-provider-k8s version
      placeholder: "The version of garm-provider-k8s used in your environment."
    validations:
      required: true

  - type: textarea
    id: kubeVersion
    attributes:
      label: Kubernetes version
      placeholder: "$kubectl version"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Anything else you would like to add?
