# SPDX-License-Identifier: MIT

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: garm-server
  namespace: runner
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
