# SPDX-License-Identifier: MIT

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    garm: server
  name: garm-server
  namespace: garm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      garm: server
  template:
    metadata:
      labels:
        garm: server
    spec:
      containers:
        - image: localhost:5000/garm-with-k8s:latest
          name: garm-server
          imagePullPolicy: Always
          env:
            - name: ARCH
              value: <ARCH>
      securityContext:
        runAsNonRoot: true
      serviceAccountName: garm-server
