# SPDX-License-Identifier: MIT

name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: lint and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: make build
        run: make build

      - name: make verify-license
        run: make verify-license

      - name: make test
        run: make test
